# targets:
#   $default:
#     builders:
#       source_gen|combining_builder:
#         generate_for:
#           - lib/src/domain/**.dart
#         options:
#           build_extensions:
#             '^lib/src/{{}}.dart': 'lib/generated/{{}}.g.dart'
#       freezed:
#         enabled: true
#         options:
#           build_extensions:
#             '^lib/src/{{}}.dart': 'lib/generated/{{}}.g.dart'
#             '^lib/routers/{{}}.dart': 'lib/generated/{{}}.freezed.dart'
