name: sharing_memo
description: 'A new Flutter project.'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Riverpod
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 모델 패턴 관리
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # 로컬 DB
  shared_preferences: ^2.3.3

  # 스플래시
  flutter_native_splash: ^2.4.3

  # 이미지
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  lottie: ^3.2.0

  # 플러터 토스트
  fluttertoast: ^8.2.8

  # 파일 경로
  path: ^1.9.0
  path_provider: ^2.1.4

  # 라우터
  go_router: ^14.6.2

  # 로케이션 / 포매터
  intl: ^0.19.0

  # Firebase 인증
  firebase_auth: ^5.4.0
  firebase_core: ^3.10.0
  google_sign_in: ^6.2.2

  # UUID
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  riverpod_generator: ^2.6.3
  go_router_builder: ^2.7.1
  source_gen: ^1.5.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
